name: Run Python Tests
on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler
          protoc --version        
          python -m pip install --upgrade pip
          python -m pip install poetry
          pip --version
          poetry --version
          # Check if poetry lock file is current with pyproject.toml
          poetry check --lock
          # Must be able to install without QA/gcld3/protobuf-compile
          poetry install --with=dev --no-ansi
          # Install with QA/gcld3
          poetry install --with=dev --no-ansi --extras qa

      - name: Run db/test with MySQL docker
        run: |
          sudo apt update
          sudo apt install -y mysql-client
          cd arxiv && poetry run pytest auth/legacy/tests --db=mysql

      - name: Run arxiv-base tests with coverage
      # Run tests with high coverage first
        run: |
          poetry run pytest --cov=arxiv.base --cov=arxiv.metadata --cov-fail-under=85 arxiv
          poetry run pytest --cov=fourohfour --cov-fail-under=74 fourohfour --cov-append
          poetry run pytest --cov=arxiv --cov-fail-under=82 arxiv --cov-append

      # - name: Check Types
      # TODO The types are in bad shape and need to be fixed
      #   run: poetry run mypy --exclude "test*" -p arxiv

      # https://github.com/mozilla/geckodriver/releases
      # When there is a new driver, you'd need to update immediately
      - name: Install Firefox ESR and test driver
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt update
          sudo apt install -y firefox-esr
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/geckodriver

      - name: Run other tests
        # These tests are split out because their coverage is low
        run: poetry run pytest --cov=arxiv --cov-fail-under=40 arxiv --ignore=arxiv/base --ignore=arxiv/auth/legacy --db=sqlite --cov-append --cov-report=html
      #- name: Check Doc Style
      #  run: poetry run pydocstyle --convention=numpy --add-ignore=D401 arxiv

      - name: Run App Tests
        run: poetry run python tests/run_app_tests.py

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: coverage-report
          path: htmlcov/
          retention-days: 30

